### ISSUE TITLE
Do you have an opinion on how to use promises on Android?

### ISSUE THREAD

**Issue by kenstir** [mxcl/AmA#12]
I have found nothing like PromiseKit in the Android world, and I want it.  Do you have an opinion?  So far I have found:

- jdeferred, 7KLOC but not much activity
- agera, 14KLOC and much more activity, rx-like
- RxJava, 280KLOC and intimidating

**Comment by mxcl** [comment]
Last time I looked I didn't find anything good, but the last Android app I wrote I used Kotlin and found the async/await system there pretty good.

**Comment by kenstir** [comment]
Thank you, I will check out Kotlin async/await!

**Comment by bellebethcooper** [comment]
@kenstir I've only dabbled a little in Android (using Kotlin) but I liked using [Kovenant](https://github.com/mplatvoet/kovenant) for promises there.

**Comment by kenstir** [comment]
@bellebethcooper This is by now an old thread, but thank you for the suggestion, though I didn't take it.  I am instead using Kotlin coroutines, and they are pretty wonderful once you get the hang of them. 
 Return `Result<>` from your suspend funs, don't try to `throw` across the coroutine boundary, and you could be very happy.
