### ISSUE TITLE
Vim or Emacs?

### ISSUE THREAD

**Issue by vinitkumar** [mxcl/AmA#15]
Do you use any of these and if so why you prefer one over another?

**Comment by mxcl** [comment]
I use TextMate, Xcode and VSCode, and have always preferred a GUI editor. When I have to (ssh, etc.) I use vim, but I am no master by any means. I have never used Emacs.

I have learned all the tricks I can with the editors I use, but ultimately I find getting text into the editor is not my bottleneck so I have not sought more efficient ways to do this.

No doubt if I was a master of VIM or Emacs I would love it and benefit. But my goal is to crank out products and taking the time to learn and then master VIM or Emacs is not worth it to me.

**Comment by vinitkumar** [comment]
@mxcl Thanks for an honest and good answer.  
> But my goal is to crank out products

Thanks for all that you do :) :+1:
