### ISSUE TITLE
New Website

### ISSUE THREAD

**Issue by CarlosVitr** [mxcl/AmA#27]
Have you ever thought about remodeling your site, adding a blog and putting Medium posts on it, I saw a problem with the **bitcoin frame**, it slightly breaks it and maybe put the project on an interesting serious page.  _*Jekyll*_ is a great solution.  I really like Homebrew, a great Package Management solution.

**Comment by mxcl** [comment]
I remodel it every few years.

> adding a blog and putting Medium posts on it

I have Medium posts, but have little interest in blogging regularly. Anyone who wants to find them can find them.

> Jekyll is a great solution

I like writing my own.

>  I really like Homebrew, a great Package Management solution.

Thanks.
